### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by MustafaElshani** [mortazavilab/lapa#15]
Following the google colab `jupyter notebook`, I ran all the code prior to prepare config and `gtf` and `fa` dsuccesfully however when I ran the following
```
! lapa  --alignment sample_config.csv \
        --fasta /home/mustafa/projects/ReferenceGenomes/gencode/v41/GRCh38.primary_assembly.genome.fa \
        --annotation gencode.v41.primary_assembly.annotation.utr_fixed.gtf \
        --chrom_sizes gencode.v41.chrom_sizes \
        --output_dir LAPA_PolyAClusterCalling
```

After a while i get the error below 
```
/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/count.py:594: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_all = df.groupby(cols).agg('sum').reset_index()
/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/count.py:598: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  _df = _df.groupby(cols).agg('sum').reset_index()
/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/count.py:598: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  _df = _df.groupby(cols).agg('sum').reset_index()
/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/count.py:598: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  _df = _df.groupby(cols).agg('sum').reset_index()
/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/count.py:598: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  _df = _df.groupby(cols).agg('sum').reset_index()
/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/count.py:598: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  _df = _df.groupby(cols).agg('sum').reset_index()
/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/count.py:598: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  _df = _df.groupby(cols).agg('sum').reset_index()
Traceback (most recent call last):
  File "/root/miniconda3/envs/LAPA/bin/lapa", line 8, in <module>
    sys.exit(cli_lapa())
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/main.py", line 112, in cli_lapa
    lapa(alignment, fasta, annotation, chrom_sizes, output_dir,
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/lapa.py", line 497, in lapa
    _lapa(alignment)
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/lapa.py", line 288, in __call__
    df_all_count, sample_counts = self.counting(alignment)
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/lapa.py", line 143, in counting
    counter._to_bigwig(df_all_count, sample_counts, self.chrom_sizes,
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/count.py", line 561, in _to_bigwig
    save_count_bw(df_all, output_dir, chrom_sizes, f'all_{prefix}')
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/count.py", line 197, in save_count_bw
    BaseCounter._to_bigwig(df, chrom_sizes, output_dir, prefix)
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/count.py", line 153, in _to_bigwig
    bw_from_pyranges(
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/lapa/utils/io.py", line 153, in bw_from_pyranges
    gr['+'].to_bigwig(bw_pos_file, chromosome_sizes=chrom_sizes,
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/pyranges/pyranges.py", line 5381, in to_bigwig
    result = _to_bigwig(self, path, chromosome_sizes, rpm, divide, value_col, dryrun)
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/pyranges/out.py", line 189, in _to_bigwig
    gr = self.to_rle(rpm=rpm, strand=False, value_col=value_col).to_ranges()
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/pyranges/pyranges.py", line 5745, in to_rle
    return _to_rle(self, value_col, strand=strand, rpm=rpm, nb_cpu=nb_cpu)
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/pyranges/methods/to_rle.py", line 22, in _to_rle
    result = pyrange_apply_single(coverage, ranges, **kwargs)
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/pyranges/multithreaded.py", line 382, in pyrange_apply_single
    result = call_f_single(function, nparams, df, **kwargs)
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/pyranges/multithreaded.py", line 31, in call_f_single
    return f.remote(df, **kwargs)
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/pyrle/methods.py", line 167, in coverage
    runs, values = _coverage(_df.Position.values, _df.Value.values)
  File "pyrle/src/coverage.pyx", line 67, in pyrle.src.coverage._coverage
  File "/root/miniconda3/envs/LAPA/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
``` 

lapa was installed with `pip` in a new conda environment python=3.8

**Comment by MuhammedHasan** [comment]
HI @MustafaElshani, I made a new release. The issue is due to the problem in PyRanges and should be fixed now.
