### ISSUE TITLE
ValueError: Invalid win_type gaussian

### ISSUE THREAD

**Issue by sunqiangzai** [mortazavilab/lapa#26]
`/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/count.py:594: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
Traceback (most recent call last):
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/bin/lapa", line 33, in <module>
    sys.exit(load_entry_point('lapa==0.0.5', 'console_scripts', 'lapa')())
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/main.py", line 112, in cli_lapa
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/lapa.py", line 497, in lapa
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/lapa.py", line 293, in __call__
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/lapa.py", line 149, in clustering
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 377, in to_df
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 378, in <listcomp>
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 255, in to_dict
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 135, in to_dict
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 118, in peak
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pandas/core/generic.py", line 11986, in rolling
    return Window(
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 165, in __init__
    self._validate()
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 1168, in _validate
    raise ValueError(f"Invalid win_type {self.win_type}")
ValueError: Invalid win_type gaussian`

**Comment by sunqiangzai** [comment]
`/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/count.py:594: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
Traceback (most recent call last):
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/bin/lapa", line 33, in <module>
    sys.exit(load_entry_point('lapa==0.0.5', 'console_scripts', 'lapa')())
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/main.py", line 112, in cli_lapa
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/lapa.py", line 497, in lapa
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/lapa.py", line 293, in __call__
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/lapa.py", line 149, in clustering
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 377, in to_df
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 378, in <listcomp>
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 255, in to_dict
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 135, in to_dict
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 118, in peak
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pandas/core/generic.py", line 11986, in rolling
    return Window(
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 165, in __init__
    self._validate()
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 1168, in _validate
    raise ValueError(f"Invalid win_type {self.win_type}")
ValueError: Invalid win_type gaussian`

**Comment by sunqiangzai** [comment]
/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/count.py:594: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
Traceback (most recent call last):
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/bin/lapa", line 33, in <module>
    sys.exit(load_entry_point('lapa==0.0.5', 'console_scripts', 'lapa')())
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/main.py", line 112, in cli_lapa
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/lapa.py", line 497, in lapa
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/lapa.py", line 293, in __call__
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/lapa.py", line 149, in clustering
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 377, in to_df
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 378, in <listcomp>
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 255, in to_dict
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 135, in to_dict
  File "/home/sutai/.local/lib/python3.10/site-packages/lapa-0.0.5-py3.10.egg/lapa/cluster.py", line 118, in peak
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pandas/core/generic.py", line 11986, in rolling
    return Window(
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 165, in __init__
    self._validate()
  File "/home/sutai/biosoft/localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 1168, in _validate
    raise ValueError(f"Invalid win_type {self.win_type}")
ValueError: Invalid win_type gaussian

**Comment by x1han** [comment]
caused by scipy.
pip install pandas==1.3.5 scipy==1.7.3
